### ISSUE TITLE
facing `UnhandledPromiseRejectionWarning: Error: Request failed with status code 403` on making API requests.

### ISSUE THREAD

**Issue by greed2411** [Link-/starred_search#13]
```sh
λ starred_search --user 'link-' --find 'es6' -d
(node:12837) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/home/greyhound/.nvm/versions/node/v14.15.0/lib/node_modules/starred_search/bin/starred_search:1212:15)
    at settle (/home/greyhound/.nvm/versions/node/v14.15.0/lib/node_modules/starred_search/bin/starred_search:1471:12)
    at IncomingMessage.handleStreamEnd (/home/greyhound/.nvm/versions/node/v14.15.0/lib/node_modules/starred_search/bin/starred_search:598:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

λ starred_search --version
0.1.10

λ node --version 
v14.15.0
````

I installed using `npm install starred_search -g`
The operating system is `Ubuntu 20.04 LTS in WSL1`.

I'm not a nodejs person, but these warnings/errors are not fetching any results, yields 403. README didn't say anything about adding keys.
Is there anything i'm doing wrong?

**Comment by Link-** [comment]
Thank you for reporting this @greed2411 - Let me try to reproduce the error

**Comment by Link-** [comment]
I tried this both in a container and on a Windows machine and it worked on both :( You don't need any keys as the API used is accessible without authentication up to 60 calls per hour.

![DEED26C4-481A-481C-9053-0FA86BF2AFBC](https://user-images.githubusercontent.com/568794/123555854-93323f80-d788-11eb-91f5-e09dcf0c6c4d.png)

Can I bother you to try uninstalling it and installing again?

```sh
$ npm uninstall starred_search -g
$ npm install starred_search -g
$ starred_search --user 'link-' --find 'es6' -V -d
```

**Comment by greed2411** [comment]
hey @Link- thanks for responding.

I uninstalled and installed it again. 
```
starred_search --user 'link-' --find 'es6' -V -d
```

this worked once, magically. 
![image](https://user-images.githubusercontent.com/21098186/123624473-34be9d00-d82c-11eb-93cc-a9e06193dede.png)


but after that I'm facing the same error again. I'm not sure if you can reproduce this tho.

![image](https://user-images.githubusercontent.com/21098186/123624117-d2fe3300-d82b-11eb-868e-ec1286b6cae2.png)

**Comment by Link-** [comment]
@greed2411 I suspect this is related to caching, I will keep testing until I'm able to replicate.

**Comment by Link-** [comment]
@greed2411 I'm not able to replicate this issue. The `403` is due to hitting the rate limit. The rate limit for unauthenticated requests to the GitHub APIs (which this tool does) is `60` `per hour` `per IP address`. 

I'm starting to think that you might have something else running and/or sharing your IP with another service that's causing this API rate limit failure.

Is this something you can investigate?
